# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856e1a1a3f67041bce9aa22f4e570d4b6e9b1dc93c90eab8a715b00bc3c81724965f2b37836a8001f543bc6482b4f94e06c5c2ca9281d6f3fed1ee57976684bb

test:
  secret_key_base: 3c2f6ab638774522d7edd5a77e83cc603bf4ceb5878964466e51ec688329463f51944a5b102bfa7db8f5d97bfa45856f25a0f607d014ae792d9c171256474319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
